export const items = [
  {
    id: 0,
    name: "stone",
    quantity: 0,
    price: 0.5,
    category: "ores and logs",
  },
  {
    id: 1,
    name: "copper",
    quantity: 0,
    price: 4.5,
    category: "ores and logs",
  },
  {
    id: 2,
    name: "Iron",
    quantity: 0,
    price: 1.6,
    category: "ores and logs",
  },
  {
    id: 3,
    name: "tungsten",
    quantity: 0,
    price: 3.2,
    category: "ores and logs",
  },
  {
    id: 4,
    name: "sulfur",
    quantity: 0,
    price: 2.5,
    category: "ores and logs",
  },
  {
    id: 5,
    name: "coal",
    quantity: 0,
    price: 1.5,
    category: "ores and logs",
  },
  {
    id: 6,
    name: "flint",
    quantity: 0,
    price: 1.8,
    category: "ores and logs",
  },
  {
    id: 7,
    name: "saltrock",
    quantity: 0,
    price: 2,
    category: "ores and logs",
  },
  {
    id: 8,
    name: "gold nugget",
    quantity: 0,
    price: 4,
    category: "valuable",
  },
  {
    id: 9,
    name: "silver nugget",
    quantity: 0,
    price: 0.9,
    category: "valuable",
  },
  {
    id: 10,
    name: "rare diamond",
    quantity: 0,
    price: 50,
    category: "valuable",
  },
  {
    id: 11,
    name: "rare emerald",
    quantity: 0,
    price: 40,
    category: "valuable",
  },
  {
    id: 12,
    name: "rare ruby",
    quantity: 0,
    price: 30,
    category: "valuable",
  },
  {
    id: 13,
    name: "gold bar",
    quantity: 0,
    price: 440,
    category: "valuable",
  },
  {
    id: 14,
    name: "silver bar",
    quantity: 0,
    price: 100,
    category: "valuable",
  },
  {
    id: 15,
    name: "wood",
    quantity: 0,
    price: 1.9,
    category: "ores and logs",
  },
  {
    id: 16,
    name: "hardwood",
    quantity: 0,
    price: 1.9,
    category: "ores and logs",
  },
  {
    id: 17,
    name: "stone bag",
    quantity: 0,
    price: 5,
    category: "delivery",
  },
  {
    id: 18,
    name: "coal bag",
    quantity: 0,
    price: 15,
    category: "delivery",
  },
  {
    id: 19,
    name: "log bundle",
    quantity: 0,
    price: 15,
    category: "delivery",
  },
  {
    id: 20,
    name: "hardwood bundle",
    quantity: 0,
    price: 15,
    category: "delivery",
  },
  {
    id: 21,
    name: "saltbag",
    quantity: 0,
    price: 18,
    category: "delivery",
  },
  {
    id: 22,
    name: "moonshine",
    quantity: 0,
    price: 10,
    category: "delivery",
  },
  {
    id: 23,
    name: "gold watch",
    quantity: 0,
    price: 25,
    category: "Valuable",
  },
  {
    id: 24,
    name: "gem bag",
    quantity: 0,
    price: 21,
    category: "Valuable",
  },
  {
    id: 25,
    name: "gold coin",
    quantity: 0,
    price: 17,
    category: "Valuable",
  },
  {
    id: 26,
    name: "gold tooth",
    quantity: 0,
    price: 12,
    category: "Valuable",
  },
  {
    id: 27,
    name: "belt buckle",
    quantity: 0,
    price: 11,
    category: "Valuable",
  },
  {
    id: 28,
    name: "bank bond",
    quantity: 0,
    price: 240,
    category: "valuable",
  },
  {
    id: 29,
    name: "medical herbs",
    quantity: 0,
    price: 3,
    category: "Herb",
  },
  {
    id: 30,
    name: "edible herbs",
    quantity: 0,
    price: 2.5,
    category: "Herb",
  },
  {
    id: 31,
    name: "fish",
    quantity: 0,
    price: 3,
    category: "food",
  },
  {
    id: 32,
    name: "meats",
    quantity: 0,
    price: 4,
    category: "food",
  },
  {
    id: 32,
    name: "pocket wagons",
    quantity: 0,
    price: 250,
    category: "vehicle",
  },
  {
    id: 32,
    name: "alloy steel",
    quantity: 0,
    price: 13,
    category: "crafted",
  },
  {
    id: 32,
    name: "scrap metal",
    quantity: 0,
    price: 11,
    category: "crafted",
  },
  {
    id: 32,
    name: "gun powder",
    quantity: 0,
    price: 15,
    category: "crafted",
  },
  {
    id: 33,
    name: "jewelry",
    quantity: 0,
    price: 25,
    category: "jewely",
  },
];
